config/routes.rb
BreathingRoom::Application.routes.draw do

  controller :sessions do
    get 'login' => :new, :as => :new_session
    post 'login' => :create
    post 'logout' => :destroy, :as => :logout
  end

  resources :users
  resources :students

  root :to => 'students#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image
  attr_accessible :body, :title
  validates :title, :body, :presence => true
end

app/models/student.rb
class Student < ActiveRecord::Base

  attr_accessible :acceptance_of_terms, :address, :altphone, :birthdate, :current_health, :email, :emergency_contact_name, :emergency_contact_phone, :how_found, :name, :phone, :prior_experience

  validates :acceptance_of_terms, :acceptance => true

  validates :name, :address, :phone, :emergency_contact_name, :emergency_contact_phone, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest

  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless logged_in?
      flash[:error] = "Please log in first"
      redirect_to new_session_path
    end
  end

  def logged_in?
    !!current_user
  end

  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id.to_s
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid Login"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "welcome!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BreathingRoom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    
  </div>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, :class => "flash #{key}" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for(@student, :html => { :class => "form-vertical" }) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :name %>
    <%= f.input :birthdate %>
    <%= f.input :address %>
    <%= f.input :phone %>
    <%= f.input :altphone %>
    <%= f.input :emergency_contact_name %>
    <%= f.input :emergency_contact_phone %>
    <%= f.email_field :email %>
    <%= f.input :how_found %>
    <%= f.input :prior_experience %>
    <%= f.input :current_health %>
    <%= f.input :acceptance_of_terms %>
    <%= f.submit :class => "btn" %>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Birthdate</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Altphone</th>
    <th>Emergency contact name</th>
    <th>Emergency contact phone</th>
    <th>Email</th>
    <th>How found</th>
    <th>Prior experience</th>
    <th>Current health</th>
    <th>Acceptance of terms</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.birthdate %></td>
    <td><%= student.address %></td>
    <td><%= student.phone %></td>
    <td><%= student.altphone %></td>
    <td><%= student.emergency_contact_name %></td>
    <td><%= student.emergency_contact_phone %></td>
    <td><%= student.email %></td>
    <td><%= student.how_found %></td>
    <td><%= student.prior_experience %></td>
    <td><%= student.current_health %></td>
    <td><%= student.acceptance_of_terms %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @student.birthdate %>
</p>

<p>
  <b>Address:</b>
  <%= @student.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @student.phone %>
</p>

<p>
  <b>Altphone:</b>
  <%= @student.altphone %>
</p>

<p>
  <b>Emergency contact name:</b>
  <%= @student.emergency_contact_name %>
</p>

<p>
  <b>Emergency contact phone:</b>
  <%= @student.emergency_contact_phone %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<p>
  <b>How found:</b>
  <%= @student.how_found %>
</p>

<p>
  <b>Prior experience:</b>
  <%= @student.prior_experience %>
</p>

<p>
  <b>Current health:</b>
  <%= @student.current_health %>
</p>

<p>
  <b>Acceptance of terms:</b>
  <%= @student.acceptance_of_terms %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>